spring.application.name=society-management

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/SM
spring.datasource.username=root
spring.datasource.password=krutartha1596
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# DIALECT
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

razorpay.key_id=rzp_test_S6yXGMGUIXfhXr
razorpay.key_secret=zYbd5RToAKnsg5MT9NgNYbJT



# ===============================
# SERVER
# ===============================
server.port=8082


